<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'
const canvasRef=ref(null);let frame=0;let onMove;let onLeave;let onResize
onMounted(()=>{const canvas=canvasRef.value;const ctx=canvas.getContext('2d');const mouse={x:-999,y:-999};const draw=()=>{const rect=canvas.getBoundingClientRect();ctx.clearRect(0,0,canvas.width,canvas.height);for(let x=15;x<canvas.width;x+=25){for(let y=15;y<canvas.height;y+=25){const dx=mouse.x-x,dy=mouse.y-y,d=Math.hypot(dx,dy),f=Math.max(0,1-d/115);ctx.fillStyle=f?`rgba(231,121,63,${.25+f*.75})`:'rgba(46,89,67,.22)';ctx.fillRect(Math.round(x+dx*f*.18),Math.round(y+dy*f*.18),2+f*5,2+f*5)}}frame=requestAnimationFrame(draw)};onResize=()=>{const r=canvas.getBoundingClientRect();canvas.width=r.width*devicePixelRatio;canvas.height=r.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);canvas.width=r.width;canvas.height=r.height};onMove=e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top};onLeave=()=>{mouse.x=-999;mouse.y=-999};onResize();addEventListener('resize',onResize);canvas.addEventListener('mousemove',onMove);canvas.addEventListener('mouseleave',onLeave);draw()})
onBeforeUnmount(()=>{cancelAnimationFrame(frame);removeEventListener('resize',onResize);canvasRef.value?.removeEventListener('mousemove',onMove);canvasRef.value?.removeEventListener('mouseleave',onLeave)})
</script>
<template><div class="lab-page"><header><p>FOX PLAYGROUND / 001</p><h1>狐狸实验室</h1><span>这里存放交互实验、视觉草图和那些还不能被称为项目的有趣尝试。</span></header><section class="experiment"><canvas ref="canvasRef"></canvas><div><small>INTERACTIVE GRID · MOVE YOUR CURSOR</small><svg viewBox="0 0 64 64"><path d="m8 11 15 11h18l15-11-5 35-19 14-19-14L8 11Z"/><path class="face" d="m18 35 14 8 14-8-5 15-9 7-9-7-5-15Z"/></svg><h2>让网格记住鼠标经过的风。</h2><p>源自旧个人主页 PlayGround 的交互点阵实验，现在由狐狸接管。</p></div></section><section class="coming"><span>02</span><h3>下一项实验正在发芽</h3><p>Canvas、WebGL、视差、声音可视化……保持好奇。</p></section></div></template>
<style scoped>
.lab-page{padding:2rem 0 5rem}header{padding:3rem 0 3.5rem}header p{color:var(--c-accent);font-size:.68rem;letter-spacing:.15em;font-weight:700}header h1{font:500 clamp(3rem,8vw,6rem) Georgia,"Songti SC",serif!important;letter-spacing:-.06em!important;margin:1.2rem 0!important}header span{color:var(--c-text-mute)}.experiment{height:520px;position:relative;background:#1e4835;border-radius:20px 20px 75px 20px;overflow:hidden;color:#fffaf0}.experiment canvas{position:absolute;inset:0;width:100%;height:100%}.experiment>div{position:absolute;inset:0;padding:3rem;pointer-events:none}.experiment small{letter-spacing:.12em;color:#d7e0d3;font-size:.62rem}.experiment svg{position:absolute;right:3rem;top:3rem;width:80px;fill:#e7793f}.experiment svg .face{fill:#fff3df}.experiment h2{font:500 clamp(2.3rem,6vw,4.6rem)/1.05 Georgia,"Songti SC",serif!important;max-width:680px;margin-top:8rem!important}.experiment p{color:#d7e0d3}.coming{margin-top:1rem;padding:2rem;border:1px dashed var(--c-border);border-radius:15px}.coming span{color:var(--c-accent);font-size:.7rem}.coming h3{font:500 1.4rem Georgia,"Songti SC",serif!important;margin:.7rem 0!important}.coming p{color:var(--c-text-mute);font-size:.8rem}@media(max-width:650px){header{padding-top:1.5rem}.experiment{height:490px}.experiment>div{padding:1.6rem}.experiment svg{right:1.6rem;top:1.6rem;width:60px}.experiment h2{margin-top:8rem!important}}
</style>
