<script setup>
const projects = [
  { no:'01',type:'交互与性能',title:'一刻短剧 Yike',desc:'一个高仿抖音的短剧 SPA。复刻核心交互，并在性能优化、数据架构与工程化上深入实践；采用“播一预一”机制实现流畅滑动体验。',tech:['Vue 3','Vite','Pinia','Sass','Express'],demo:'https://danoandholidays.github.io/yike/',code:'https://github.com/DanoAndHolidays/yike' },
  { no:'02',type:'数据与可视化',title:'深岩智测',desc:'基于多维信息感知的煤岩损伤演化预警平台，将模型预测结果封装成易于理解的数据可视化界面。',tech:['Vue 3','Vue Router','Pinia','TailwindCSS','ECharts'],demo:'https://danoandholidays.github.io/test/#/',code:'https://github.com/DanoAndHolidays/test' },
  { no:'03',type:'移动端实验',title:'PLAYLET-APP',desc:'早期短剧应用原型，专注移动端竖屏播放体验的二次开发与交互探索。',tech:['JavaScript','HTML5','CSS3'],demo:'https://danoandholidays.github.io/PLAYLET-APP/',code:'https://github.com/DanoAndHolidays/PLAYLET-APP' },
]
</script>
<template><div class="projects-page"><header><p>SELECTED WORK</p><h1>在真实问题里，<br><span>把想法做出来。</span></h1><div><span>03 个已发布项目</span><span>Vue · TypeScript · 数据可视化</span></div></header><section><article v-for="project in projects" :key="project.no"><div class="number">{{ project.no }}</div><div class="project-main"><small>{{ project.type }}</small><h2>{{ project.title }}</h2><p>{{ project.desc }}</p><div class="tech"><span v-for="item in project.tech" :key="item">{{ item }}</span></div></div><div class="links"><a :href="project.demo" target="_blank" rel="noreferrer">在线演示 ↗</a><a :href="project.code" target="_blank" rel="noreferrer">查看代码 ↗</a></div></article></section></div></template>
<style scoped>
.projects-page{padding:2rem 0 5rem}header{padding:3rem 0 4rem;border-bottom:1px solid var(--c-border)}header>p{font-size:.68rem;color:var(--c-accent);letter-spacing:.15em;font-weight:700}h1{font:500 clamp(3rem,8vw,6.2rem)/.98 Georgia,"Songti SC",serif!important;letter-spacing:-.06em!important;margin:1.4rem 0 2.5rem!important}h1 span{color:var(--c-accent);font-style:italic}header>div{display:flex;justify-content:space-between;color:var(--c-text-mute);font-size:.72rem}article{display:grid;grid-template-columns:70px 1fr 130px;gap:2rem;padding:2.5rem 0;border-bottom:1px solid var(--c-border)}.number{color:var(--c-accent);font-size:.75rem}.project-main small{color:var(--c-accent);font-size:.66rem;letter-spacing:.1em}.project-main h2{font:500 2rem Georgia,"Songti SC",serif!important;margin:1rem 0!important}.project-main p{color:var(--c-text-mute);line-height:1.8;max-width:650px}.tech{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:1.5rem}.tech span{border:1px solid var(--c-border);border-radius:99px;padding:.4rem .7rem;font-size:.65rem}.links{display:flex;flex-direction:column;gap:.8rem}.links a{color:var(--c-text);font-size:.75rem;text-decoration:none}.links a:hover{color:var(--c-accent)}@media(max-width:700px){article{grid-template-columns:35px 1fr}.links{grid-column:2;flex-direction:row}.projects-page header{padding-top:1.5rem}header>div{gap:1rem}h1{font-size:3.2rem!important}}
</style>
